from __future__ import annotations
import io
import json
import re
import zipfile
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, StreamingResponse
from pydantic import BaseModel

import config
from musicweb import tracker, get_user_email

router = APIRouter()

_CHAPTER_IDS = ["starthere", "summary", "flowcharts", "scale", "midi", "ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8"]

_STYLE = (
    "<style>"
    "body{font-family:Arial,sans-serif;font-size:13px;color:#e2e4ed;background:#0b0c10;padding:12px;}"
    "h2{color:#7c65d9;border-left:4px solid #7c65d9;padding-left:8px;}"
    "h3{color:#00d4b6;} p,li{color:#e2e4ed;margin-bottom:6px;}"
    "table{border-collapse:collapse;width:100%;margin:8px 0;}"
    "th{background:#1a1c26;color:#00d4b6;padding:6px;border:1px solid #2d3041;}"
    "td{padding:6px;border:1px solid #2d3041;color:#e2e4ed;}"
    "code{background:#151720;color:#a6e3a1;padding:2px 4px;border-radius:3px;font-family:monospace;}"
    "pre{background:#151720;color:#cdd6f4;padding:10px;border-radius:6px;border:1px solid #2d3041;}"
    "</style>"
)

_FLOWCHARTS_HTML = (
    f"<html><head>{_STYLE}</head><body>"
    '<h2 style="color:#7c65d9;border-left:4px solid #7c65d9;padding-left:8px;margin-bottom:16px">Flowcharts</h2>'
    '<div style="margin-bottom:20px;text-align:center">'
    '<p style="color:#8a8f9e;font-size:12px;margin-bottom:8px">How Nyx-Step Works</p>'
    '<img src="/static/images/nyx-step-how-it-works.png" '
    'alt="How Nyx-Step Works" '
    'style="max-width:100%;border-radius:8px;border:1px solid #2d3041">'
    '</div>'
    '<div style="margin-bottom:20px;text-align:center">'
    '<p style="color:#8a8f9e;font-size:12px;margin-bottom:8px">How AI Creates Music From Static (Audio Diffusion Process)</p>'
    '<img src="/static/images/nyx-audio-diffusion.png" '
    'alt="How AI Creates Music From Static" '
    'style="max-width:100%;border-radius:8px;border:1px solid #2d3041">'
    '</div>'
    '<div style="margin-bottom:20px;text-align:center">'
    '<p style="color:#8a8f9e;font-size:12px;margin-bottom:8px">Nyx AI Music Keyword &amp; Tag Library</p>'
    '<img src="/static/images/nyx-keyword-library.png" '
    'alt="Nyx AI Music Keyword &amp; Tag Library" '
    'style="max-width:100%;border-radius:8px;border:1px solid #2d3041">'
    '</div>'
    "</body></html>"
)


_START_HERE_HTML = (
    f"<html><head>{_STYLE}</head><body>"
    '<h2 style="color:#7c65d9;border-left:4px solid #7c65d9;padding-left:8px;margin-bottom:16px">Start Here</h2>'
    '<div style="text-align:center">'
    '<img src="/static/images/nyx-start-here.png" '
    'alt="From Blank Slate to Beatmaker: A Musical Journey with Nyx AI" '
    'style="max-width:100%;border-radius:8px;border:1px solid #2d3041">'
    '</div>'
    "</body></html>"
)


_SCALE_HTML = (
    f"<html><head>{_STYLE}</head><body>"
    '<h2 style="color:#7c65d9;border-left:4px solid #7c65d9;padding-left:8px;margin-bottom:16px">Scales &amp; Modes in Nyx-Step</h2>'

    '<h3>How It Works</h3>'
    '<p>Scale, Key, and Mode are injected as plain-text tags into the generation caption that Nyx-Step\'s Qwen language model reads. '
    'There is no hard-wired music-theory engine — the model interprets <code>C Blues</code> or <code>Phrygian mode</code> the same way '
    'a human musician would when reading a brief. This means <strong>any standard music-theory term Qwen understands will influence the output</strong>, '
    'but it does not guarantee that every note lands on that scale. Think of it as harmonic colour and mood shaping, not strict enforcement.</p>'
    '<p>Example caption fragment generated by the Style Infusor fields:</p>'
    '<pre>C Dorian mode, 120 BPM, 4/4, jazz piano trio, upbeat, swing</pre>'

    '<h3>Reliability by Category</h3>'
    '<table>'
    '<tr><th>Category</th><th>Examples</th><th>Reliability</th><th>Notes</th></tr>'
    '<tr><td>Standard</td><td>Major, Minor, Harmonic Minor, Melodic Minor</td><td style="color:#4caf50">High</td>'
    '<td>Core of Western music training data — very consistent effect on harmonic character</td></tr>'
    '<tr><td>Pentatonic / Blues</td><td>Pentatonic Minor, Blues, Blues Major</td><td style="color:#4caf50">High</td>'
    '<td>Extremely common in pop, rock, jazz training data; Blues gives that characteristic flat-3 / flat-7 feel</td></tr>'
    '<tr><td>Church Modes</td><td>Dorian, Phrygian, Lydian, Mixolydian, Aeolian, Locrian, Ionian</td><td style="color:#4caf50">High</td>'
    '<td>All seven modes appear extensively in music descriptions; each has a well-understood character the model reliably reproduces</td></tr>'
    '<tr><td>Symmetric</td><td>Whole Tone, Diminished, Chromatic</td><td style="color:#8bc34a">Good</td>'
    '<td>Strong presence in jazz and film scoring literature; Whole Tone gives dreamy/impressionist quality, Diminished adds tension</td></tr>'
    '<tr><td>Jazz Modes</td><td>Lydian Dominant, Super Locrian, Altered, Acoustic, Bebop Major/Dominant</td><td style="color:#8bc34a">Good</td>'
    '<td>Standard jazz vocabulary; Bebop and Altered are especially well represented in jazz training data</td></tr>'
    '<tr><td>World / Exotic</td><td>Hungarian Minor, Double Harmonic Major, Phrygian Dominant, Persian, Neapolitan</td><td style="color:#ff9800">Moderate</td>'
    '<td>Qwen knows these terms; audio training data coverage is sparser — effect on timbre and mood is real but subtler</td></tr>'
    '<tr><td>Ethnic Modes</td><td>Bhairav, Bhairavi, Yaman, Kafi, Hijaz</td><td style="color:#ff9800">Moderate</td>'
    '<td>Indian classical and Middle Eastern raga/maqam names; works best when combined with matching genre tags (e.g. <code>sitar, tabla, hindustani</code>)</td></tr>'
    '</table>'

    '<h3>Scale vs Mode — Which to Use</h3>'
    '<p>The Scale and Mode fields are independent — both get appended to the caption as separate tags. You can use one or both:</p>'
    '<ul>'
    '<li><strong>Scale only</strong> — use when you want the full scale character without specifying a diatonic mode. '
    'e.g. <code>C Blues</code>, <code>A Hungarian Minor</code></li>'
    '<li><strong>Mode only</strong> — use when the mode identity matters most. '
    'e.g. <code>Dorian mode</code>, <code>Phrygian mode</code></li>'
    '<li><strong>Both</strong> — can cause mild contradiction (e.g. <code>C Major</code> + <code>Dorian mode</code>). '
    'Generally safe if the scale and mode are compatible, but prefer one or the other when they overlap.</li>'
    '<li><strong>Neither</strong> — for genres where key/scale is implied by the style tags alone '
    '(e.g. <code>blues guitar</code> already implies a blues scale without stating it explicitly).</li>'
    '</ul>'

    '<h3>Scale Character Reference</h3>'
    '<table>'
    '<tr><th>Scale / Mode</th><th>Sound Character</th><th>Works Well With</th></tr>'
    '<tr><td>Major</td><td>Bright, resolved, happy</td><td>Pop, country, classical, upbeat EDM</td></tr>'
    '<tr><td>Natural Minor (Aeolian)</td><td>Dark, melancholic, emotional</td><td>Rock, metal, ballads, film scores</td></tr>'
    '<tr><td>Harmonic Minor</td><td>Exotic tension, dramatic resolution</td><td>Classical, flamenco, metal, Middle Eastern</td></tr>'
    '<tr><td>Melodic Minor</td><td>Smooth minor with lifted 6th &amp; 7th</td><td>Jazz, neo-classical, sophisticated R&amp;B</td></tr>'
    '<tr><td>Dorian</td><td>Minor but slightly brighter — cool, jazzy</td><td>Jazz, funk, blues-rock, Celtic, Daft Punk-style</td></tr>'
    '<tr><td>Phrygian</td><td>Dark, Spanish/flamenco, tense</td><td>Flamenco, metal, dark electronic, Middle Eastern</td></tr>'
    '<tr><td>Lydian</td><td>Dreamy, floating, otherworldly (raised 4th)</td><td>Film scores, synth pop, ambient, Sakamoto-style</td></tr>'
    '<tr><td>Mixolydian</td><td>Major with a flat 7 — bluesy, rock-ish</td><td>Blues, rock, Celtic, folk, classic rock</td></tr>'
    '<tr><td>Locrian</td><td>Unstable, dissonant, unsettling</td><td>Avant-garde, horror film, extreme metal</td></tr>'
    '<tr><td>Pentatonic Minor</td><td>Universal minor without tension tones</td><td>Blues, rock, pop, virtually any genre</td></tr>'
    '<tr><td>Pentatonic Major</td><td>Bright, open, simple</td><td>Folk, country, children\'s music, pop</td></tr>'
    '<tr><td>Blues</td><td>Soulful, expressive — pentatonic minor + flat 5</td><td>Blues, jazz, rock, R&amp;B, soul</td></tr>'
    '<tr><td>Whole Tone</td><td>Ambiguous, floating, impressionist</td><td>Film, ambient, Debussy-style, dream sequences</td></tr>'
    '<tr><td>Diminished</td><td>Tense, angular, horror or jazz</td><td>Jazz (over dom7b9), horror, avant-garde</td></tr>'
    '<tr><td>Hungarian Minor</td><td>Exotic, Eastern European, dramatic</td><td>Folk, metal, film, world music</td></tr>'
    '<tr><td>Phrygian Dominant</td><td>Spanish / Middle Eastern (Phrygian #3)</td><td>Flamenco, Middle Eastern, surf guitar</td></tr>'
    '<tr><td>Lydian Dominant</td><td>Lydian with flat 7 — bright yet funky</td><td>Jazz fusion, film, Lydian-flavoured rock</td></tr>'
    '<tr><td>Super Locrian (Altered)</td><td>Maximum dissonance — jazz tension</td><td>Over dominant chords in jazz</td></tr>'
    '<tr><td>Bebop Dominant</td><td>Mixolydian + passing tone — swinging</td><td>Jazz, bebop, swing</td></tr>'
    '<tr><td>Hijaz</td><td>Arabic/Middle Eastern character</td><td>World music, fusion, film</td></tr>'
    '</table>'

    '<h3>Tips for Best Results</h3>'
    '<ul>'
    '<li>Combine scale/mode with matching genre tags — <code>C Dorian mode, jazz, electric piano</code> is stronger than the scale alone</li>'
    '<li>The Chord Progression field reinforces scale choices — a <code>i - VI - III - VII</code> progression with <code>Dorian mode</code> is very effective</li>'
    '<li>For ethnic scales (Bhairav, Hijaz, Persian), always pair with cultural instrument tags for the model to anchor the sound</li>'
    '<li>Locrian and Super Locrian rarely sound "right" as a whole-piece scale — best used for short passages or extreme tension effects</li>'
    '<li>If outputs sound harmonically wrong, try dropping the mode field and letting the genre tags carry the harmonic character</li>'
    '</ul>'
    "</body></html>"
)


_MIDI_HTML = (
    f"<html><head>{_STYLE}</head><body>"
    '<h2 style="color:#7c65d9;border-left:4px solid #7c65d9;padding-left:8px;margin-bottom:16px">MIDI Extraction</h2>'

    '<h3>What It Does</h3>'
    '<p>The MIDI tab converts audio recordings into MIDI files you can load directly into any DAW (Ableton, FL Studio, Logic, Reaper). '
    'Two extraction engines are available depending on the source material:</p>'
    '<table>'
    '<tr><th>Mode</th><th>Engine</th><th>Best For</th><th>Output</th></tr>'
    '<tr><td><strong>Melody</strong></td><td>librosa pyin</td>'
    '<td>Any single melodic instrument — vocals, guitar, violin, flute, synth lead</td>'
    '<td>Monophonic MIDI — one note at a time</td></tr>'
    '<tr><td><strong>Piano</strong></td><td>Piano Transcription Inference (neural)</td>'
    '<td>Piano recordings — acoustic and electric</td>'
    '<td>Polyphonic MIDI — full chord and voice detection</td></tr>'
    '</table>'

    '<h3>Melody Mode — Tips</h3>'
    '<ul>'
    '<li>Works on any monophonic (single-note) source — it uses pitch detection (pyin), not note onset prediction</li>'
    '<li>Set the <strong>BPM</strong> field to the tempo of the audio before extracting — use the Analyze tab to auto-detect BPM first</li>'
    '<li>Very quiet or heavily reverbed recordings may produce extra short spurious notes — these can be cleaned up in your DAW</li>'
    '<li>Notes shorter than 50 ms are automatically filtered to reduce noise</li>'
    '<li>Background harmony, chords, or other instruments are ignored — only the dominant pitch is tracked</li>'
    '</ul>'

    '<h3>Piano Mode — Tips</h3>'
    '<ul>'
    '<li>Uses a GPU-accelerated neural model trained specifically on piano recordings</li>'
    '<li>Works best on dry or lightly reverbed piano — heavy processing or mixed-down tracks may produce extra ghost notes</li>'
    '<li>BPM is not required for piano mode — the model works in real time without a tempo reference</li>'
    '<li>Full polyphony: chords, bass lines, and treble melody are all captured simultaneously</li>'
    '<li>Output MIDI velocity reflects note loudness from the audio</li>'
    '</ul>'

    '<h3>Workflow</h3>'
    '<ol>'
    '<li>Go to the <strong>Analyze</strong> tab and upload the audio — note the detected BPM</li>'
    '<li>Switch to the <strong>MIDI</strong> tab, select Mode and enter the BPM if using Melody mode</li>'
    '<li>Upload the same audio file and click <strong>Extract MIDI</strong></li>'
    '<li>Download the .mid file and import it into your DAW</li>'
    '<li>Quantize in your DAW if needed — pyin outputs raw timing, not quantized to a grid</li>'
    '</ol>'

    '<h3>What To Do With The MIDI</h3>'
    '<ul>'
    '<li><strong>Re-orchestrate</strong> — trigger any soft-synth or sample library with the extracted melody</li>'
    '<li><strong>Transpose</strong> — move the melody to a different key for remixing</li>'
    '<li><strong>Chord detection</strong> — use the MIDI piano roll to see what chords the AI generated, then build a real arrangement</li>'
    '<li><strong>Feed back to ACE-Step</strong> — use extracted note data to write better chord progression tags for the next generation</li>'
    '</ul>'
    "</body></html>"
)


def _parse_chapter(section_id: str) -> str:
    """Extract one <h2 id="section_id">...</h2> section from Aceuser.html."""
    if section_id == "starthere":
        return _START_HERE_HTML
    if section_id == "flowcharts":
        return _FLOWCHARTS_HTML
    if section_id == "scale":
        return _SCALE_HTML
    if section_id == "midi":
        return _MIDI_HTML
    if not config.ACEUSER_HTML.exists():
        return "<p>Guide file not found.</p>"
    raw = config.ACEUSER_HTML.read_text(encoding="utf-8")
    chunks = re.split(r'(?=<h2\s)', raw)
    for chunk in chunks:
        m = re.search(r'<h2[^>]*id="([^"]+)"', chunk)
        if m and m.group(1) == section_id:
            return f"<html><head>{_STYLE}</head><body>{chunk}</body></html>"
    if section_id == "summary":
        return f"<html><head>{_STYLE}</head><body><p style='color:#8a8f9e'>No summary content found.</p></body></html>"
    return f"<p>Section '{section_id}' not found.</p>"


@router.get("/guide/{section_id}", response_class=HTMLResponse)
async def guide_section(section_id: str):
    if section_id not in _CHAPTER_IDS:
        return HTMLResponse("<p>Invalid section.</p>", status_code=404)
    return HTMLResponse(_parse_chapter(section_id))


@router.get("/meta/{filename}")
async def meta(filename: str, request: Request):
    user_email = get_user_email(request)
    if not tracker.user_owns_file(user_email, filename):
        return JSONResponse({"error": "File not found or access denied"}, status_code=404)

    # Search history.jsonl for the record that contains this file
    try:
        if config.HISTORY_LOG.exists():
            with open(config.HISTORY_LOG) as f:
                for line in reversed(f.readlines()):
                    try:
                        record = json.loads(line)
                        if filename in record.get("output_files", []):
                            record.pop("user_email", None)
                            return JSONResponse(record)
                    except Exception:
                        continue
    except Exception:
        pass

    # Fall back to in-memory tracker if history doesn't have it yet
    with tracker._lock:
        for job in tracker._jobs.values():
            if filename in job.output_files and job.user_email == user_email:
                return JSONResponse({
                    "prompt_id": job.prompt_id,
                    "song_name": job.song_name,
                    "caption": job.caption,
                    "seed": job.seed,
                    "params": job.params,
                    "output_files": job.output_files,
                    "timestamp": job.submitted_at.isoformat(),
                })

    return JSONResponse({"error": "Metadata not found"}, status_code=404)


def _tag_audio(file_path: Path, meta: dict | None) -> bytes | None:
    """Return file bytes with ID3/FLAC tags applied from meta. Returns None on failure."""
    if not meta:
        return None
    try:
        ext = file_path.suffix.lower()
        raw = file_path.read_bytes()
        buf = io.BytesIO(raw)
        title   = meta.get("song_name", "")
        caption = meta.get("caption", "")
        seed    = str(meta.get("seed", ""))
        comment = f"Tags: {caption}\nSeed: {seed}" if caption else f"Seed: {seed}"

        if ext == ".mp3":
            from mutagen.mp3 import MP3
            from mutagen.id3 import ID3, TIT2, TPE1, COMM, ID3NoHeaderError
            audio = MP3(buf)
            try:
                tags = audio.tags or ID3()
            except ID3NoHeaderError:
                tags = ID3()
            tags.add(TIT2(encoding=3, text=title))
            tags.add(TPE1(encoding=3, text="Nyx-Step AI"))
            tags.add(COMM(encoding=3, lang="eng", desc="", text=comment))
            out = io.BytesIO()
            tags.save(out)
            # Prepend ID3 header to raw MP3 data (tags go at start)
            out.seek(0)
            return out.read() + raw

        elif ext in (".flac",):
            from mutagen.flac import FLAC
            audio = FLAC(buf)
            audio["title"]   = title
            audio["artist"]  = "Nyx-Step AI"
            audio["comment"] = comment
            out = io.BytesIO()
            audio.save(out)
            out.seek(0)
            return out.read()

    except Exception:
        pass
    return None


def _get_meta_for_file(filename: str) -> dict | None:
    """Look up job metadata for a filename from history or in-memory tracker."""
    try:
        if config.HISTORY_LOG.exists():
            with open(config.HISTORY_LOG) as f:
                for line in reversed(f.readlines()):
                    try:
                        record = json.loads(line)
                        if filename in record.get("output_files", []):
                            return record
                    except Exception:
                        continue
    except Exception:
        pass
    with tracker._lock:
        for job in tracker._jobs.values():
            if filename in job.output_files:
                return {"song_name": job.song_name, "caption": job.caption, "seed": job.seed}
    return None


@router.get("/download/{filename}")
async def download(filename: str, request: Request):
    user_email = get_user_email(request)

    if not tracker.user_owns_file(user_email, filename):
        return JSONResponse({"error": "File not found or access denied"}, status_code=404)

    file_path = config.COMFYUI_OUTPUT_DIR / filename
    if not file_path.exists():
        return JSONResponse({"error": "File not on disk"}, status_code=404)

    ext = file_path.suffix.lower()
    media_type = {"mp3": "audio/mpeg", "flac": "audio/flac", "opus": "audio/ogg"}.get(ext.lstrip("."), "audio/mpeg")

    # Try to serve with embedded metadata tags
    meta = _get_meta_for_file(filename)
    tagged = _tag_audio(file_path, meta)
    if tagged:
        return StreamingResponse(
            io.BytesIO(tagged),
            media_type=media_type,
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "Cache-Control": "no-store, no-cache, must-revalidate",
                "Pragma": "no-cache",
            },
        )

    return FileResponse(
        path=str(file_path),
        media_type=media_type,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Cache-Control": "no-store, no-cache, must-revalidate",
            "Pragma": "no-cache",
        },
    )


class _ZipRequest(BaseModel):
    filenames: list[str]
    zip_name: str = "musicweb_batch.zip"


@router.post("/download/zip")
async def download_zip(req: _ZipRequest, request: Request):
    user_email = get_user_email(request)
    if not req.filenames:
        return JSONResponse({"error": "No filenames provided"}, status_code=400)
    if len(req.filenames) > 50:
        return JSONResponse({"error": "Max 50 files per ZIP"}, status_code=400)

    buf = io.BytesIO()
    added = 0
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in req.filenames:
            if not tracker.user_owns_file(user_email, fname):
                continue
            fpath = config.COMFYUI_OUTPUT_DIR / fname
            if fpath.exists():
                zf.write(fpath, fname)
                added += 1

    if added == 0:
        return JSONResponse({"error": "No accessible files found"}, status_code=404)

    buf.seek(0)
    safe_name = re.sub(r"[^\w.\-]", "_", req.zip_name)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}"'},
    )
