"""
LRC Synchronized Lyrics
Approximates time-aligned lyrics from a generated audio file + raw lyrics text.

Algorithm:
  1. Load audio, compute RMS energy envelope at ~10 Hz
  2. Detect phrase boundaries: sustained low-energy gaps > gap_threshold seconds
  3. Distribute lyric lines across detected phrase start times
  4. If more lyric lines than phrase starts: evenly interpolate remaining times
  5. Return LRC text and optionally save a .lrc file alongside the audio

This is a heuristic approximation — not the DiT attention-alignment method
used by the standalone ACE-Step API — but it produces playable LRC files for
standard music players.
"""
from __future__ import annotations
import asyncio
import concurrent.futures
import re
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse, PlainTextResponse
from pydantic import BaseModel

import config
from musicweb import get_user_email

router = APIRouter()
_executor = concurrent.futures.ThreadPoolExecutor(max_workers=2)


def _fmt_lrc_time(seconds: float) -> str:
    minutes = int(seconds // 60)
    secs = seconds % 60
    return f"[{minutes:02d}:{secs:05.2f}]"


def _split_lyrics(text: str) -> list[str]:
    """Split lyrics into non-empty lines, stripping section markers."""
    lines = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped:
            continue
        # ACE-Step section brackets like [Verse], [Chorus] — keep as metadata but skip for timing
        if re.match(r"^\[[A-Za-z\s]+\]$", stripped):
            continue
        lines.append(stripped)
    return lines


def _generate_lrc(audio_path: Path, lyrics_text: str, bpm: float) -> str:
    """CPU-bound work — runs in executor."""
    import numpy as np

    try:
        import librosa
        y, sr = librosa.load(str(audio_path), mono=True, sr=22050)
    except Exception as exc:
        return f"[00:00.00]LRC generation failed: {exc}"

    lines = _split_lyrics(lyrics_text)
    if not lines:
        return "[00:00.00]No lyrics"

    duration = len(y) / sr

    # ── Phrase boundary detection via RMS energy ───────────────────────────────
    frame_length = 2048
    hop = 512
    rms = librosa.feature.rms(y=y, frame_length=frame_length, hop_length=hop)[0]
    times = librosa.frames_to_time(np.arange(len(rms)), sr=sr, hop_length=hop)

    # Threshold = 20th percentile of non-silent frames
    threshold = np.percentile(rms[rms > 0], 20) if (rms > 0).any() else 0.01
    is_silent = rms < threshold

    # Find transitions from silent → active (phrase starts)
    phrase_starts = [0.0]  # always include t=0
    min_gap = 0.8  # seconds of silence before counting as a new phrase
    min_phrase = 1.5  # minimum seconds between phrase starts
    in_silence = False
    silence_start = 0.0

    for i, (t, sil) in enumerate(zip(times, is_silent)):
        if sil and not in_silence:
            in_silence = True
            silence_start = t
        elif not sil and in_silence:
            in_silence = False
            gap = t - silence_start
            if gap >= min_gap:
                candidate = t
                if candidate - phrase_starts[-1] >= min_phrase:
                    phrase_starts.append(candidate)

    # If we have too few boundaries, subdivide based on BPM
    beats_per_line = max(4, int(bpm / 15))  # ~4 beats per line
    beat_duration = 60.0 / max(bpm, 40)
    line_duration = beat_duration * beats_per_line

    if len(phrase_starts) < len(lines):
        last = phrase_starts[-1]
        while len(phrase_starts) < len(lines) and last + line_duration < duration - 1:
            last += line_duration
            phrase_starts.append(round(last, 2))

    # Trim to duration
    phrase_starts = [t for t in phrase_starts if t < duration - 0.5]

    # ── Assign lyrics → times ──────────────────────────────────────────────────
    lrc_lines = []
    for i, line in enumerate(lines):
        if i < len(phrase_starts):
            t = phrase_starts[i]
        else:
            # Overflow: continue from last known time + line_duration
            t = phrase_starts[-1] + (i - len(phrase_starts) + 1) * line_duration
        t = min(t, duration - 0.1)
        lrc_lines.append((t, line))

    header = (
        f"[ti:Generated by Nyx-Step]\n"
        f"[ar:Nyx Studios]\n"
        f"[length:{int(duration//60):02d}:{duration%60:.2f}]\n"
    )
    body = "\n".join(f"{_fmt_lrc_time(t)}{line}" for t, line in lrc_lines)
    return header + body


class LRCRequest(BaseModel):
    filename: str
    lyrics: str
    bpm: float = 120.0
    save: bool = True


@router.post("/lrc/generate")
async def generate_lrc(request: Request, body: LRCRequest):
    get_user_email(request)

    # Find audio file
    audio_path: Path | None = None
    for search_dir in [config.COMFYUI_OUTPUT_DIR, config.COMFYUI_OUTPUT_DIR / "audio"]:
        candidate = search_dir / body.filename
        if candidate.exists():
            audio_path = candidate
            break
    if audio_path is None:
        for p in config.COMFYUI_OUTPUT_DIR.rglob(body.filename):
            audio_path = p
            break
    if audio_path is None:
        return JSONResponse({"error": f"Audio file not found: {body.filename}"}, status_code=404)

    loop = asyncio.get_event_loop()
    lrc_content = await loop.run_in_executor(
        _executor, lambda: _generate_lrc(audio_path, body.lyrics, body.bpm)
    )

    if body.save:
        lrc_path = audio_path.with_suffix(".lrc")
        lrc_path.write_text(lrc_content, encoding="utf-8")

    return {"lrc": lrc_content, "filename": audio_path.stem + ".lrc"}


@router.get("/lrc/download/{filename}")
async def download_lrc(filename: str, request: Request):
    get_user_email(request)
    lrc_path: Path | None = None
    for p in config.COMFYUI_OUTPUT_DIR.rglob(filename):
        lrc_path = p
        break
    if lrc_path is None:
        return JSONResponse({"error": "LRC file not found"}, status_code=404)
    return PlainTextResponse(
        lrc_path.read_text(encoding="utf-8"),
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
